(define-constant OWNER tx-sender)
(define-constant ERR_NO_AUTHORITY 10001)
(define-constant ERR_POS_INVALID 10002)

(define-data-var m_master_contract (optional principal) none)
(define-data-var a (buff 20) 0x)
(define-data-var b (buff 48) 0x)
(define-data-var c principal OWNER)
(define-data-var d (optional (buff 20)) none)

(define-public (set_master_contract (contract_owner principal))
  (begin
    (asserts! (is-eq tx-sender OWNER) (err ERR_NO_AUTHORITY))
    (ok (and (is-none (var-get m_master_contract)) (var-set m_master_contract (some contract_owner))))
  )
)

(define-public (transfer (index uint) (namespace (buff 20)) (name (buff 48)) (new_owner principal) (zonefile (optional (buff 20))))
  (begin
    (asserts! (is-eq contract-caller (unwrap-panic (var-get m_master_contract))) (err ERR_NO_AUTHORITY))
    (asserts! (and (>= index u1) (<= index u500)) (err ERR_POS_INVALID))
    (var-set a namespace)
    (var-set b name)
    (var-set c new_owner)
    (var-set d zonefile)
    (if (<= index u125)
      (transfer1 (to-int index))
      (transfer2 (to-int index))
    )
  )
)

(define-private (transfer1 (i int))
  (if (<= i 63) (if (<= i 32) (if (<= i 16) (if (<= i 8) (if (is-eq i 1) (f1) (if (is-eq i 2) (f2) (if (is-eq i 3) (f3) (if (is-eq i 4) (f4) (if (is-eq i 5) (f5) (if (is-eq i 6) (f6) (if (is-eq i 7) (f7) (if (is-eq i 8) (f8) (err 0))))))))) (if (is-eq i 9) (f9) (if (is-eq i 10) (f10) (if (is-eq i 11) (f11) (if (is-eq i 12) (f12) (if (is-eq i 13) (f13) (if (is-eq i 14) (f14) (if (is-eq i 15) (f15) (if (is-eq i 16) (f16) (err 0))))))))))
  (if (<= i 24) (if (is-eq i 17) (f17) (if (is-eq i 18) (f18) (if (is-eq i 19) (f19) (if (is-eq i 20) (f20) (if (is-eq i 21)  (f21) (if (is-eq i 22)  (f22) (if (is-eq i 23)  (f23) (if (is-eq i 24)  (f24) (err 0))))))))) (if (is-eq i 25) (f25) (if (is-eq i 26) (f26) (if (is-eq i 27) (f27) (if (is-eq i 28) (f28) (if (is-eq i 29) (f29) (if (is-eq i 30) (f30) (if (is-eq i 31) (f31) (if (is-eq i 32) (f32) (err 0)))))))))))
  (if (<= i 48) (if (<= i 40) (if (is-eq i 33) (f33) (if (is-eq i 34) (f34) (if (is-eq i 35) (f35) (if (is-eq i 36) (f36) (if (is-eq i 37) (f37) (if (is-eq i 38) (f38) (if (is-eq i 39) (f39) (if (is-eq i 40) (f40) (err 0))))))))) (if (is-eq i 41) (f41) (if (is-eq i 42) (f42) (if (is-eq i 43) (f43) (if (is-eq i 44) (f44) (if (is-eq i 45) (f45) (if (is-eq i 46) (f46) (if (is-eq i 47) (f47) (if (is-eq i 48) (f48) (err 0))))))))))
  (if (<= i 56) (if (is-eq i 49) (f49) (if (is-eq i 50) (f50) (if (is-eq i 51) (f51) (if (is-eq i 52) (f52) (if (is-eq i 53) (f53) (if (is-eq i 54) (f54) (if (is-eq i 55) (f55) (if (is-eq i 56) (f56) (err 0))))))))) (if (is-eq i 57) (f57) (if (is-eq i 58) (f58) (if (is-eq i 59) (f59) (if (is-eq i 60) (f60) (if (is-eq i 61) (f61) (if (is-eq i 62) (f62) (if (is-eq i 63) (f63) (err 0)))))))))))
  (if (<= i 94) (if (<= i 79) (if (<= i 71) (if (is-eq i 64) (f64) (if (is-eq i 65) (f65) (if (is-eq i 66) (f66) (if (is-eq i 67) (f67) (if (is-eq i 68) (f68) (if (is-eq i 69) (f69) (if (is-eq i 70) (f70) (if (is-eq i 71) (f71) (err 0))))))))) (if (is-eq i 72) (f72) (if (is-eq i 73) (f73) (if (is-eq i 74) (f74) (if (is-eq i 75) (f75) (if (is-eq i 76) (f76) (if (is-eq i 77) (f77) (if (is-eq i 78) (f78) (if (is-eq i 79) (f79) (err 0))))))))))
  (if (<= i 87) (if (is-eq i 80) (f80) (if (is-eq i 81) (f81) (if (is-eq i 82) (f82) (if (is-eq i 83) (f83) (if (is-eq i 84) (f84) (if (is-eq i 85) (f85) (if (is-eq i 86) (f86) (if (is-eq i 87) (f87) (err 0))))))))) (if (is-eq i 88) (f88) (if (is-eq i 89) (f89) (if (is-eq i 90) (f90) (if (is-eq i 91) (f91) (if (is-eq i 92) (f92) (if (is-eq i 93) (f93) (if (is-eq i 94) (f94) (err 0))))))))))
  (if (<= i 110) (if (<= i 102) (if (is-eq i 95) (f95) (if (is-eq i 96) (f96) (if (is-eq i 97) (f97) (if (is-eq i 98) (f98) (if (is-eq i 99) (f99) (if (is-eq i 100) (f100) (if (is-eq i 101) (f101) (if (is-eq i 102) (f102) (err 0))))))))) (if (is-eq i 103) (f103) (if (is-eq i 104) (f104) (if (is-eq i 105) (f105) (if (is-eq i 106) (f106) (if (is-eq i 107) (f107) (if (is-eq i 108) (f108) (if (is-eq i 109) (f109) (if (is-eq i 110) (f110) (err 0))))))))))
  (if (<= i 118) (if (is-eq i 111) (f111) (if (is-eq i 112) (f112) (if (is-eq i 113) (f113) (if (is-eq i 114) (f114) (if (is-eq i 115) (f115) (if (is-eq i 116) (f116) (if (is-eq i 117) (f117) (if (is-eq i 118) (f118) (err 0))))))))) (if (is-eq i 119) (f119) (if (is-eq i 120) (f120) (if (is-eq i 121) (f121) (if (is-eq i 122) (f122) (if (is-eq i 123) (f123) (if (is-eq i 124) (f124) (if (is-eq i 125) (f125) (err 0)))))))))))))

(define-private (transfer2 (i int))
  (if (<= i 188) (if (<= i 157) (if (<= i 141) (if (<= i 133) (if (is-eq i 126) (f126) (if (is-eq i 127) (f127) (if (is-eq i 128) (f128) (if (is-eq i 129) (f129) (if (is-eq i 130) (f130) (if (is-eq i 131) (f131) (if (is-eq i 132) (f132) (if (is-eq i 133) (f133) (err 0))))))))) (if (is-eq i 134) (f134) (if (is-eq i 135) (f135) (if (is-eq i 136) (f136) (if (is-eq i 137) (f137) (if (is-eq i 138) (f138) (if (is-eq i 139) (f139) (if (is-eq i 140) (f140) (if (is-eq i 141) (f141) (err 0))))))))))
  (if (<= i 149) (if (is-eq i 142) (f142) (if (is-eq i 143) (f143) (if (is-eq i 144) (f144) (if (is-eq i 145) (f145) (if (is-eq i 146)  (f146) (if (is-eq i 147)  (f147) (if (is-eq i 148)  (f148) (if (is-eq i 149)  (f149) (err 0))))))))) (if (is-eq i 150) (f150) (if (is-eq i 151) (f151) (if (is-eq i 152) (f152) (if (is-eq i 153) (f153) (if (is-eq i 154) (f154) (if (is-eq i 155) (f155) (if (is-eq i 156) (f156) (if (is-eq i 157) (f157) (err 0)))))))))))
  (if (<= i 173) (if (<= i 165) (if (is-eq i 158) (f158) (if (is-eq i 159) (f159) (if (is-eq i 160) (f160) (if (is-eq i 161) (f161) (if (is-eq i 162) (f162) (if (is-eq i 163) (f163) (if (is-eq i 164) (f164) (if (is-eq i 165) (f165) (err 0))))))))) (if (is-eq i 166) (f166) (if (is-eq i 167) (f167) (if (is-eq i 168) (f168) (if (is-eq i 169) (f169) (if (is-eq i 170) (f170) (if (is-eq i 171) (f171) (if (is-eq i 172) (f172) (if (is-eq i 173) (f173) (err 0))))))))))
  (if (<= i 181) (if (is-eq i 174) (f174) (if (is-eq i 175) (f175) (if (is-eq i 176) (f176) (if (is-eq i 177) (f177) (if (is-eq i 178) (f178) (if (is-eq i 179) (f179) (if (is-eq i 180) (f180) (if (is-eq i 181) (f181) (err 0))))))))) (if (is-eq i 182) (f182) (if (is-eq i 183) (f183) (if (is-eq i 184) (f184) (if (is-eq i 185) (f185) (if (is-eq i 186) (f186) (if (is-eq i 187) (f187) (if (is-eq i 188) (f188) (err 0)))))))))))
  (if (<= i 219) (if (<= i 204) (if (<= i 196) (if (is-eq i 189) (f189) (if (is-eq i 190) (f190) (if (is-eq i 191) (f191) (if (is-eq i 192) (f192) (if (is-eq i 193) (f193) (if (is-eq i 194) (f194) (if (is-eq i 195) (f195) (if (is-eq i 196) (f196) (err 0))))))))) (if (is-eq i 197) (f197) (if (is-eq i 198) (f198) (if (is-eq i 199) (f199) (if (is-eq i 200) (f200) (if (is-eq i 201) (f201) (if (is-eq i 202) (f202) (if (is-eq i 203) (f203) (if (is-eq i 204) (f204) (err 0))))))))))
  (if (<= i 212) (if (is-eq i 205) (f205) (if (is-eq i 206) (f206) (if (is-eq i 207) (f207) (if (is-eq i 208) (f208) (if (is-eq i 209) (f209) (if (is-eq i 210) (f210) (if (is-eq i 211) (f211) (if (is-eq i 212) (f212) (err 0))))))))) (if (is-eq i 213) (f213) (if (is-eq i 214) (f214) (if (is-eq i 215) (f215) (if (is-eq i 216) (f216) (if (is-eq i 217) (f217) (if (is-eq i 218) (f218) (if (is-eq i 219) (f219) (err 0))))))))))
  (if (<= i 235) (if (<= i 227) (if (is-eq i 220) (f220) (if (is-eq i 221) (f221) (if (is-eq i 222) (f222) (if (is-eq i 223) (f223) (if (is-eq i 224) (f224) (if (is-eq i 225) (f225) (if (is-eq i 226) (f226) (if (is-eq i 227) (f227) (err 0))))))))) (if (is-eq i 228) (f228) (if (is-eq i 229) (f229) (if (is-eq i 230) (f230) (if (is-eq i 231) (f231) (if (is-eq i 232) (f232) (if (is-eq i 233) (f233) (if (is-eq i 234) (f234) (if (is-eq i 235) (f235) (err 0))))))))))
  (if (<= i 243) (if (is-eq i 236) (f236) (if (is-eq i 237) (f237) (if (is-eq i 238) (f238) (if (is-eq i 239) (f239) (if (is-eq i 240) (f240) (if (is-eq i 241) (f241) (if (is-eq i 242) (f242) (if (is-eq i 243) (f243) (err 0))))))))) (if (is-eq i 244) (f244) (if (is-eq i 245) (f245) (if (is-eq i 246) (f246) (if (is-eq i 247) (f247) (if (is-eq i 248) (f248) (if (is-eq i 249) (f249) (if (is-eq i 250) (f250) (err 0)))))))))))))

(define-private (f1) (contract-call? .a251 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f2) (contract-call? .a252 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f3) (contract-call? .a253 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f4) (contract-call? .a254 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f5) (contract-call? .a255 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f6) (contract-call? .a256 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f7) (contract-call? .a257 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f8) (contract-call? .a258 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f9) (contract-call? .a259 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f10) (contract-call? .a260 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f11) (contract-call? .a261 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f12) (contract-call? .a262 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f13) (contract-call? .a263 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f14) (contract-call? .a264 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f15) (contract-call? .a265 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f16) (contract-call? .a266 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f17) (contract-call? .a267 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f18) (contract-call? .a268 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f19) (contract-call? .a269 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f20) (contract-call? .a270 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f21) (contract-call? .a271 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f22) (contract-call? .a272 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f23) (contract-call? .a273 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f24) (contract-call? .a274 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f25) (contract-call? .a275 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f26) (contract-call? .a276 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f27) (contract-call? .a277 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f28) (contract-call? .a278 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f29) (contract-call? .a279 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f30) (contract-call? .a280 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f31) (contract-call? .a281 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f32) (contract-call? .a282 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f33) (contract-call? .a283 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f34) (contract-call? .a284 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f35) (contract-call? .a285 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f36) (contract-call? .a286 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f37) (contract-call? .a287 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f38) (contract-call? .a288 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f39) (contract-call? .a289 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f40) (contract-call? .a290 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f41) (contract-call? .a291 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f42) (contract-call? .a292 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f43) (contract-call? .a293 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f44) (contract-call? .a294 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f45) (contract-call? .a295 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f46) (contract-call? .a296 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f47) (contract-call? .a297 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f48) (contract-call? .a298 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f49) (contract-call? .a299 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f50) (contract-call? .a300 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f51) (contract-call? .a301 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f52) (contract-call? .a302 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f53) (contract-call? .a303 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f54) (contract-call? .a304 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f55) (contract-call? .a305 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f56) (contract-call? .a306 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f57) (contract-call? .a307 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f58) (contract-call? .a308 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f59) (contract-call? .a309 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f60) (contract-call? .a310 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f61) (contract-call? .a311 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f62) (contract-call? .a312 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f63) (contract-call? .a313 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f64) (contract-call? .a314 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f65) (contract-call? .a315 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f66) (contract-call? .a316 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f67) (contract-call? .a317 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f68) (contract-call? .a318 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f69) (contract-call? .a319 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f70) (contract-call? .a320 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f71) (contract-call? .a321 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f72) (contract-call? .a322 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f73) (contract-call? .a323 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f74) (contract-call? .a324 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f75) (contract-call? .a325 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f76) (contract-call? .a326 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f77) (contract-call? .a327 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f78) (contract-call? .a328 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f79) (contract-call? .a329 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f80) (contract-call? .a330 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f81) (contract-call? .a331 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f82) (contract-call? .a332 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f83) (contract-call? .a333 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f84) (contract-call? .a334 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f85) (contract-call? .a335 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f86) (contract-call? .a336 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f87) (contract-call? .a337 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f88) (contract-call? .a338 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f89) (contract-call? .a339 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f90) (contract-call? .a340 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f91) (contract-call? .a341 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f92) (contract-call? .a342 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f93) (contract-call? .a343 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f94) (contract-call? .a344 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f95) (contract-call? .a345 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f96) (contract-call? .a346 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f97) (contract-call? .a347 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f98) (contract-call? .a348 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f99) (contract-call? .a349 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f100) (contract-call? .a350 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f101) (contract-call? .a351 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f102) (contract-call? .a352 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f103) (contract-call? .a353 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f104) (contract-call? .a354 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f105) (contract-call? .a355 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f106) (contract-call? .a356 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f107) (contract-call? .a357 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f108) (contract-call? .a358 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f109) (contract-call? .a359 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f110) (contract-call? .a360 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f111) (contract-call? .a361 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f112) (contract-call? .a362 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f113) (contract-call? .a363 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f114) (contract-call? .a364 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f115) (contract-call? .a365 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f116) (contract-call? .a366 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f117) (contract-call? .a367 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f118) (contract-call? .a368 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f119) (contract-call? .a369 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f120) (contract-call? .a370 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f121) (contract-call? .a371 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f122) (contract-call? .a372 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f123) (contract-call? .a373 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f124) (contract-call? .a374 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f125) (contract-call? .a375 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f126) (contract-call? .a376 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f127) (contract-call? .a377 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f128) (contract-call? .a378 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f129) (contract-call? .a379 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f130) (contract-call? .a380 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f131) (contract-call? .a381 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f132) (contract-call? .a382 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f133) (contract-call? .a383 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f134) (contract-call? .a384 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f135) (contract-call? .a385 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f136) (contract-call? .a386 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f137) (contract-call? .a387 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f138) (contract-call? .a388 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f139) (contract-call? .a389 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f140) (contract-call? .a390 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f141) (contract-call? .a391 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f142) (contract-call? .a392 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f143) (contract-call? .a393 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f144) (contract-call? .a394 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f145) (contract-call? .a395 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f146) (contract-call? .a396 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f147) (contract-call? .a397 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f148) (contract-call? .a398 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f149) (contract-call? .a399 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f150) (contract-call? .a400 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f151) (contract-call? .a401 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f152) (contract-call? .a402 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f153) (contract-call? .a403 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f154) (contract-call? .a404 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f155) (contract-call? .a405 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f156) (contract-call? .a406 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f157) (contract-call? .a407 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f158) (contract-call? .a408 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f159) (contract-call? .a409 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f160) (contract-call? .a410 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f161) (contract-call? .a411 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f162) (contract-call? .a412 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f163) (contract-call? .a413 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f164) (contract-call? .a414 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f165) (contract-call? .a415 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f166) (contract-call? .a416 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f167) (contract-call? .a417 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f168) (contract-call? .a418 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f169) (contract-call? .a419 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f170) (contract-call? .a420 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f171) (contract-call? .a421 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f172) (contract-call? .a422 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f173) (contract-call? .a423 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f174) (contract-call? .a424 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f175) (contract-call? .a425 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f176) (contract-call? .a426 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f177) (contract-call? .a427 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f178) (contract-call? .a428 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f179) (contract-call? .a429 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f180) (contract-call? .a430 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f181) (contract-call? .a431 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f182) (contract-call? .a432 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f183) (contract-call? .a433 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f184) (contract-call? .a434 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f185) (contract-call? .a435 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f186) (contract-call? .a436 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f187) (contract-call? .a437 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f188) (contract-call? .a438 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f189) (contract-call? .a439 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f190) (contract-call? .a440 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f191) (contract-call? .a441 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f192) (contract-call? .a442 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f193) (contract-call? .a443 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f194) (contract-call? .a444 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f195) (contract-call? .a445 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f196) (contract-call? .a446 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f197) (contract-call? .a447 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f198) (contract-call? .a448 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f199) (contract-call? .a449 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f200) (contract-call? .a450 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f201) (contract-call? .a451 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f202) (contract-call? .a452 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f203) (contract-call? .a453 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f204) (contract-call? .a454 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f205) (contract-call? .a455 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f206) (contract-call? .a456 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f207) (contract-call? .a457 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f208) (contract-call? .a458 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f209) (contract-call? .a459 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f210) (contract-call? .a460 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f211) (contract-call? .a461 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f212) (contract-call? .a462 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f213) (contract-call? .a463 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f214) (contract-call? .a464 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f215) (contract-call? .a465 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f216) (contract-call? .a466 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f217) (contract-call? .a467 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f218) (contract-call? .a468 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f219) (contract-call? .a469 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f220) (contract-call? .a470 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f221) (contract-call? .a471 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f222) (contract-call? .a472 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f223) (contract-call? .a473 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f224) (contract-call? .a474 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f225) (contract-call? .a475 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f226) (contract-call? .a476 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f227) (contract-call? .a477 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f228) (contract-call? .a478 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f229) (contract-call? .a479 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f230) (contract-call? .a480 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f231) (contract-call? .a481 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f232) (contract-call? .a482 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f233) (contract-call? .a483 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f234) (contract-call? .a484 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f235) (contract-call? .a485 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f236) (contract-call? .a486 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f237) (contract-call? .a487 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f238) (contract-call? .a488 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f239) (contract-call? .a489 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f240) (contract-call? .a490 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f241) (contract-call? .a491 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f242) (contract-call? .a492 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f243) (contract-call? .a493 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f244) (contract-call? .a494 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f245) (contract-call? .a495 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f246) (contract-call? .a496 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f247) (contract-call? .a497 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f248) (contract-call? .a498 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f249) (contract-call? .a499 transfer (var-get a) (var-get b) (var-get c) (var-get d)))
(define-private (f250) (contract-call? .a500 transfer (var-get a) (var-get b) (var-get c) (var-get d)))