;; constants
(define-constant ERR-NOT-AUTHORIZED u401)
(define-constant CONTRACT-OWNER tx-sender)

;;(define-data-var holders (string-ascii 256) "hi")


;;;;;;;;;;;;;;

(define-read-only (get-vault-by-id (vault-id uint))
  (contract-call? 'SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-vault-data-v1-1 get-vault-by-id vault-id)
)


(define-read-only (get-debt-for-vault (vault-id uint))
  (let ((vault (get-vault-by-id vault-id))) (ok (get debt vault)))
)

(print (get-vault-by-id u571))
(print (get-vault-by-id u572))
(print (get-vault-by-id u573))
(print (get-vault-by-id u574))
(print (get-vault-by-id u575))
(print (get-vault-by-id u576))
(print (get-vault-by-id u577))
(print (get-vault-by-id u578))
(print (get-vault-by-id u579))
(print (get-vault-by-id u580))
(print (get-vault-by-id u581))
(print (get-vault-by-id u582))
(print (get-vault-by-id u583))
(print (get-vault-by-id u584))
(print (get-vault-by-id u585))
(print (get-vault-by-id u586))
(print (get-vault-by-id u587))
(print (get-vault-by-id u588))
(print (get-vault-by-id u589))
(print (get-vault-by-id u590))
(print (get-vault-by-id u591))
(print (get-vault-by-id u592))
(print (get-vault-by-id u593))
(print (get-vault-by-id u594))
(print (get-vault-by-id u595))
(print (get-vault-by-id u596))
(print (get-vault-by-id u597))
(print (get-vault-by-id u598))
(print (get-vault-by-id u599))
(print (get-vault-by-id u600))
(print (get-vault-by-id u601))
(print (get-vault-by-id u602))
(print (get-vault-by-id u603))
(print (get-vault-by-id u604))
(print (get-vault-by-id u605))
(print (get-vault-by-id u606))
(print (get-vault-by-id u607))
(print (get-vault-by-id u608))
(print (get-vault-by-id u609))
(print (get-vault-by-id u610))
(print (get-vault-by-id u611))
(print (get-vault-by-id u612))
(print (get-vault-by-id u613))
(print (get-vault-by-id u614))
(print (get-vault-by-id u615))
(print (get-vault-by-id u616))
(print (get-vault-by-id u617))
(print (get-vault-by-id u618))
(print (get-vault-by-id u619))
(print (get-vault-by-id u620))
(print (get-vault-by-id u621))
(print (get-vault-by-id u622))
(print (get-vault-by-id u623))
(print (get-vault-by-id u624))
(print (get-vault-by-id u625))
(print (get-vault-by-id u626))
(print (get-vault-by-id u627))
(print (get-vault-by-id u628))
(print (get-vault-by-id u629))
(print (get-vault-by-id u630))
(print (get-vault-by-id u631))
(print (get-vault-by-id u632))
(print (get-vault-by-id u633))
(print (get-vault-by-id u634))
(print (get-vault-by-id u635))
(print (get-vault-by-id u636))
(print (get-vault-by-id u637))
(print (get-vault-by-id u638))
(print (get-vault-by-id u639))
(print (get-vault-by-id u640))
(print (get-vault-by-id u641))
(print (get-vault-by-id u642))
(print (get-vault-by-id u643))
(print (get-vault-by-id u644))
(print (get-vault-by-id u645))
(print (get-vault-by-id u646))
(print (get-vault-by-id u647))
(print (get-vault-by-id u648))
(print (get-vault-by-id u649))
(print (get-vault-by-id u650))
(print (get-vault-by-id u651))
(print (get-vault-by-id u652))
(print (get-vault-by-id u653))
(print (get-vault-by-id u654))
(print (get-vault-by-id u655))
(print (get-vault-by-id u656))
(print (get-vault-by-id u657))
(print (get-vault-by-id u658))
(print (get-vault-by-id u659))
(print (get-vault-by-id u660))
(print (get-vault-by-id u661))
(print (get-vault-by-id u662))
(print (get-vault-by-id u663))
(print (get-vault-by-id u664))
(print (get-vault-by-id u665))