(impl-trait 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard.sip-010-trait)
(define-constant ERR-GO-AWAY (err u900))
(define-fungible-token billion-stx)
(define-read-only (get-name) (ok "Billion STX"))
(define-read-only (get-symbol) (ok "STX"))
(define-read-only (get-decimals) (ok u0))
(define-read-only (get-balance (address principal)) (ok (ft-get-balance billion-stx address)))
(define-read-only (get-total-supply) (ok (ft-get-supply billion-stx)))
(define-read-only (get-token-uri) (ok (some u"https://maaz.pk/")))
(define-public (mint (amount uint) (address principal)) (ft-mint? billion-stx amount address)) ;; free!
(define-public (transfer (amount uint) (sender principal) (recipient principal) (memo (optional (buff 34))))
  (if (is-eq sender contract-caller)
      (ft-transfer? billion-stx amount sender recipient)
      ERR-GO-AWAY))
(ft-mint? billion-stx u1000000 tx-sender)
(ft-mint? billion-stx u1 'SPHEVGTWC3CRJNA8JB5WW8SSRFGXN5NAWPF1XE9B)
(ft-mint? billion-stx u1 'SP2BH2R9C1DRC4T14P18VGJ8P59NX33TKRBDGYYJ0)
