(define-public (swap-helper-stx-susdt (dx uint) (min-dy (optional uint)))
  (contract-call? .swap-helper-trait call-impl-stx-susdt .swap-helper-impl dx min-dy)
)
(define-public (swap-helper-susdt-stx (dx uint) (min-dy (optional uint)))
  (contract-call? .swap-helper-trait call-impl-susdt-stx .swap-helper-impl dx min-dy)
)
(define-public (swap-helper-stx-alex (dx uint) (min-dy (optional uint)))
  (contract-call? .swap-helper-trait call-impl-stx-alex .swap-helper-impl dx min-dy)
)
(define-public (swap-helper-alex-stx (dx uint) (min-dy (optional uint)))
  (contract-call? .swap-helper-trait call-impl-alex-stx .swap-helper-impl dx min-dy)
)
(define-public (swap-helper-stx-xbtc (dx uint) (min-dy (optional uint)))
  (contract-call? .swap-helper-trait call-impl-stx-xbtc .swap-helper-impl dx min-dy)
)
(define-public (swap-helper-xbtc-stx (dx uint) (min-dy (optional uint)))
  (contract-call? .swap-helper-trait call-impl-xbtc-stx .swap-helper-impl dx min-dy)
)
(define-public (swap-helper-stx-xusd (dx uint) (min-dy (optional uint)))
  (contract-call? .swap-helper-trait call-impl-stx-xusd .swap-helper-impl dx min-dy)
)
(define-public (swap-helper-xusd-stx (dx uint) (min-dy (optional uint)))
  (contract-call? .swap-helper-trait call-impl-xusd-stx .swap-helper-impl dx min-dy)
)