(define-public (swap-helper-stx-susdt (dx uint) (min-dz (optional uint)))
  (contract-call? .amm-swap-pool swap-helper .token-wstx .token-susdt ONE_8 dx min-dz)
)
(define-constant ONE_8 u100000000)
(define-private (mul-down (a uint) (b uint))
    (/ (* a b) ONE_8)
)
(define-private (div-down (a uint) (b uint))
  (if (is-eq a u0)
    u0
    (/ (* a ONE_8) b)
  )
)