baseURL = "https://source-of-clarity.com"
title = "Source of Clarity - Deployed Clarity Contracts"
theme = "hugo-geekdoc"

pluralizeListTitles = false

ignoreErrors = ["error-remote-getjson"]

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"

[params]
  geekdocLogo = "nexus_white.png"
  geekdocRepo = "https://github.com/boomcrypto/clarity-deployed-contracts"
  geekdocEditPath = "edit/main/docs/content"
